server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: url
    username: user
    password: passwd
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: postgresql

logging:
  level:
    root: INFO

